### ISSUE TITLE
Download Daily Data for a location

### ISSUE THREAD

**Issue by JoshThompson866** [allisonmorgan/google_trends#1]
Hi,
I'm looking for a method to download daily search index data for the **topic** of 'Flood' and 'Landslide' within a selected country (in this case, Uganda) over the past five years from google trends, is there a way I can use your software to do this?

**Comment by allisonmorgan** [comment]
Thanks for reaching out. I'd suggest you look into the [pytrends](https://github.com/GeneralMills/pytrends#interest-by-region) package, which this project imports. Just a quick glance suggests that you could change the lines in [this notebook](https://github.com/allisonmorgan/google_trends/blob/master/parse_google_trends.ipynb) from:

```python
p = request.TrendReq(guser, gpas , hl='en-US')
p.build_payload([keyword],timeframe=key)
```

to include the `geo` parameter, like such:

```python
p = request.TrendReq(guser, gpas , hl='en-US')
p.build_payload([keyword],timeframe=key, geo='UG')
```

Then calling `get_timeseries` would return a trend for Uganda. If you are interested, you can also pass multiple keywords to the pytrends `build_payload` function (i.e., `p.build_payload(['Flood', 'Landslide'], timeframe=key)`), which would allow you to get a time series of interest over multiple search terms.

**Comment by allisonmorgan** [comment]
Feel free to re-open @JoshThompson866 if the above does not meet your needs.
